name: my_input_component
description: "A new Flutter plugin project."
version: 1.0.2
homepage: "my_input_component"

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  number_text_input_formatter: ^1.0.0+8
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
